/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BudgetProgramStatus
 */
public class BudgetProgramStatusTest {
    /**
     * Model tests for BudgetProgramStatus
     */
    @Test
    public void testBudgetProgramStatus() {
        // TODO: test BudgetProgramStatus
    }

}
