/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BudgetBlueprint;
import com.konfigthis.client.model.BudgetProgramStatus;
import com.konfigthis.client.model.EmployeeFilter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BudgetProgram
 */
public class BudgetProgramTest {
    private final BudgetProgram model = new BudgetProgram();

    /**
     * Model tests for BudgetProgram
     */
    @Test
    public void testBudgetProgram() {
        // TODO: test BudgetProgram
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'budgetBlueprints'
     */
    @Test
    public void budgetBlueprintsTest() {
        // TODO: test budgetBlueprints
    }

    /**
     * Test the property 'existingBudgetIds'
     */
    @Test
    public void existingBudgetIdsTest() {
        // TODO: test existingBudgetIds
    }

    /**
     * Test the property 'employeeFilter'
     */
    @Test
    public void employeeFilterTest() {
        // TODO: test employeeFilter
    }

    /**
     * Test the property 'budgetProgramStatus'
     */
    @Test
    public void budgetProgramStatusTest() {
        // TODO: test budgetProgramStatus
    }

    /**
     * Test the property 'creatorUserId'
     */
    @Test
    public void creatorUserIdTest() {
        // TODO: test creatorUserId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
