/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CreateBudgetBlueprintRequest;
import com.konfigthis.client.model.CreateBudgetProgramRequestEmployeeFilter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateBudgetProgramRequest
 */
public class CreateBudgetProgramRequestTest {
    private final CreateBudgetProgramRequest model = new CreateBudgetProgramRequest();

    /**
     * Model tests for CreateBudgetProgramRequest
     */
    @Test
    public void testCreateBudgetProgramRequest() {
        // TODO: test CreateBudgetProgramRequest
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'existingBudgetIds'
     */
    @Test
    public void existingBudgetIdsTest() {
        // TODO: test existingBudgetIds
    }

    /**
     * Test the property 'budgetBlueprints'
     */
    @Test
    public void budgetBlueprintsTest() {
        // TODO: test budgetBlueprints
    }

    /**
     * Test the property 'employeeFilter'
     */
    @Test
    public void employeeFilterTest() {
        // TODO: test employeeFilter
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
