/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EmploymentStatus;
import com.konfigthis.client.model.EmploymentType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeFilter
 */
public class EmployeeFilterTest {
    private final EmployeeFilter model = new EmployeeFilter();

    /**
     * Model tests for EmployeeFilter
     */
    @Test
    public void testEmployeeFilter() {
        // TODO: test EmployeeFilter
    }

    /**
     * Test the property 'employmentStatus'
     */
    @Test
    public void employmentStatusTest() {
        // TODO: test employmentStatus
    }

    /**
     * Test the property 'employmentType'
     */
    @Test
    public void employmentTypeTest() {
        // TODO: test employmentType
    }

}
