/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BudgetLimit;
import com.konfigthis.client.model.BudgetLimitVisibilityType;
import com.konfigthis.client.model.LimitType;
import com.konfigthis.client.model.SpendType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateBudgetRequest
 */
public class UpdateBudgetRequestTest {
    private final UpdateBudgetRequest model = new UpdateBudgetRequest();

    /**
     * Model tests for UpdateBudgetRequest
     */
    @Test
    public void testUpdateBudgetRequest() {
        // TODO: test UpdateBudgetRequest
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ownerUserIds'
     */
    @Test
    public void ownerUserIdsTest() {
        // TODO: test ownerUserIds
    }

    /**
     * Test the property 'memberUserIds'
     */
    @Test
    public void memberUserIdsTest() {
        // TODO: test memberUserIds
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'limitType'
     */
    @Test
    public void limitTypeTest() {
        // TODO: test limitType
    }

    /**
     * Test the property 'spendType'
     */
    @Test
    public void spendTypeTest() {
        // TODO: test spendType
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'limitVisibility'
     */
    @Test
    public void limitVisibilityTest() {
        // TODO: test limitVisibility
    }

}
