/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets BudgetProgramStatus
 */
@JsonAdapter(BudgetProgramStatus.Adapter.class)public enum BudgetProgramStatus {
  
  ACTIVE("BUDGET_PROGRAM_STATUS_ACTIVE"),
  
  INACTIVE("BUDGET_PROGRAM_STATUS_INACTIVE"),
  
  DELETED("BUDGET_PROGRAM_STATUS_DELETED");

  private String value;

  BudgetProgramStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BudgetProgramStatus fromValue(String value) {
    for (BudgetProgramStatus b : BudgetProgramStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<BudgetProgramStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final BudgetProgramStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BudgetProgramStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return BudgetProgramStatus.fromValue(value);
    }
  }
}

