/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  Status of the Budget e.g. APPROVED. 
 */
@JsonAdapter(BudgetStatus.Adapter.class)public enum BudgetStatus {
  
  APPROVED("APPROVED"),
  
  EXPIRED("EXPIRED"),
  
  TERMINATED("TERMINATED"),
  
  DELETED("DELETED");

  private String value;

  BudgetStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BudgetStatus fromValue(String value) {
    for (BudgetStatus b : BudgetStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<BudgetStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final BudgetStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BudgetStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return BudgetStatus.fromValue(value);
    }
  }
}

