/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  What kind of employment the employee has. 
 */
@JsonAdapter(EmploymentType.Adapter.class)public enum EmploymentType {
  
  FULL_TIME("EMPLOYMENT_TYPE_FULL_TIME"),
  
  PART_TIME("EMPLOYMENT_TYPE_PART_TIME"),
  
  CONTRACTOR("EMPLOYMENT_TYPE_CONTRACTOR"),
  
  INTERN("EMPLOYMENT_TYPE_INTERN"),
  
  FREELANCE("EMPLOYMENT_TYPE_FREELANCE");

  private String value;

  EmploymentType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EmploymentType fromValue(String value) {
    for (EmploymentType b : EmploymentType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EmploymentType> {
    @Override
    public void write(final JsonWriter jsonWriter, final EmploymentType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EmploymentType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EmploymentType.fromValue(value);
    }
  }
}

