/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  A filter used to determine if a user adheres to a Budget Program. 
 */
@JsonAdapter(EmploymentStatus.Adapter.class)public enum EmploymentStatus {
  
  ACTIVE("EMPLOYMENT_STATUS_ACTIVE"),
  
  INACTIVE("EMPLOYMENT_STATUS_INACTIVE"),
  
  PENDING("EMPLOYMENT_STATUS_PENDING");

  private String value;

  EmploymentStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EmploymentStatus fromValue(String value) {
    for (EmploymentStatus b : EmploymentStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EmploymentStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final EmploymentStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EmploymentStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EmploymentStatus.fromValue(value);
    }
  }
}

