/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  Period type of the Budget e.g. MONTHLY. 
 */
@JsonAdapter(PeriodType.Adapter.class)public enum PeriodType {
  
  WEEKLY("WEEKLY"),
  
  MONTHLY("MONTHLY"),
  
  QUARTERLY("QUARTERLY"),
  
  YEARLY("YEARLY"),
  
  ONE_TIME("ONE_TIME");

  private String value;

  PeriodType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PeriodType fromValue(String value) {
    for (PeriodType b : PeriodType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PeriodType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PeriodType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PeriodType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PeriodType.fromValue(value);
    }
  }
}

