/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  Whether this Budget only can be spent from by cards provisioned by this Budget.  
 */
@JsonAdapter(SpendType.Adapter.class)public enum SpendType {
  
  BUDGET_PROVISIONED_CARDS_ONLY("BUDGET_PROVISIONED_CARDS_ONLY"),
  
  NON_BUDGET_PROVISIONED_CARDS_ALLOWED("NON_BUDGET_PROVISIONED_CARDS_ALLOWED");

  private String value;

  SpendType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SpendType fromValue(String value) {
    for (SpendType b : SpendType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SpendType> {
    @Override
    public void write(final JsonWriter jsonWriter, final SpendType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SpendType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SpendType.fromValue(value);
    }
  }
}

