/*
 * Budgets API
 *  The budgets API lets you manage your Brex budgets. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.BudgetProgram;
import com.konfigthis.client.model.CreateBudgetBlueprintRequest;
import com.konfigthis.client.model.CreateBudgetProgramRequest;
import com.konfigthis.client.model.CreateBudgetProgramRequestEmployeeFilter;
import com.konfigthis.client.model.PageBudgetProgram;
import com.konfigthis.client.model.UpdateBudgetBlueprintRequest;
import com.konfigthis.client.model.UpdateBudgetProgramRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BudgetProgramsApi
 */
@Disabled
public class BudgetProgramsApiTest {

    private static BudgetProgramsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new BudgetProgramsApi(apiClient);
    }

    /**
     *  Create Budget Program 
     *
     *  Creates a Budget Program. If your account does not have access to budget program features, a 403 response status will be returned. If this is the case and you want to gain access to this endpoint, please contact Brex support. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        List<CreateBudgetBlueprintRequest> budgetBlueprints = null;
        String name = null;
        String idempotencyKey = null;
        String description = null;
        List<String> existingBudgetIds = null;
        CreateBudgetProgramRequestEmployeeFilter employeeFilter = null;
        BudgetProgram response = api.create(budgetBlueprints, name, idempotencyKey)
                .description(description)
                .existingBudgetIds(existingBudgetIds)
                .employeeFilter(employeeFilter)
                .execute();
        // TODO: test validations
    }

    /**
     *  Get Budget Program 
     *
     *  Retrieves a Budget Program by ID 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String id = null;
        BudgetProgram response = api.getById(id)
                .execute();
        // TODO: test validations
    }

    /**
     *  List Budget Programs 
     *
     *  Lists Budget Programs belonging to this account 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        String cursor = null;
        Integer limit = null;
        PageBudgetProgram response = api.list()
                .cursor(cursor)
                .limit(limit)
                .execute();
        // TODO: test validations
    }

    /**
     *  Delete Budget Program 
     *
     *  Delete a Budget Program by ID. This endpoint requires budget management. If your account does not have access to budget management features, a 403 response status will be returned.  If this is the case and you want to gain access to this endpoint, please contact Brex support. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeProgramByIdTest() throws ApiException {
        String id = null;
        BudgetProgram response = api.removeProgramById(id)
                .execute();
        // TODO: test validations
    }

    /**
     *  Update Budget Program 
     *
     *  Updates a Budget Program. This endpoint requires budget management. If your account does not have access to budget management features, a 403 response status will be returned.  If this is the case and you want to gain access to this endpoint, please contact Brex support. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProgramByIdTest() throws ApiException {
        String id = null;
        String idempotencyKey = null;
        String description = null;
        List<String> existingBudgetIds = null;
        List<UpdateBudgetBlueprintRequest> budgetBlueprints = null;
        CreateBudgetProgramRequestEmployeeFilter employeeFilter = null;
        String name = null;
        BudgetProgram response = api.updateProgramById(id, idempotencyKey)
                .description(description)
                .existingBudgetIds(existingBudgetIds)
                .budgetBlueprints(budgetBlueprints)
                .employeeFilter(employeeFilter)
                .name(name)
                .execute();
        // TODO: test validations
    }

}
