openapi: 3.0.1
info:
  contact:
    email: developer-access@brex.com
    name: Admin
    url: https://brex.com
  description: |2

    The budgets API lets you manage your Brex budgets.
  title: Budgets API
  version: "1.0"
  x-konfig-has-globally-required-security: true
servers:
- description: Production
  url: https://platform.brexapis.com
- description: "Staging (Note: This is not a sandbox. It will not work with customer\
    \ tokens.)"
  url: https://platform.staging.brexapps.com
security:
- OAuth2: []
tags:
- description: Endpoints for budgets data.
  name: Budgets
- description: Endpoints for budgets programs data.
  name: Budget Programs
paths:
  /v1/budget_programs:
    get:
      description: |2

        Lists Budget Programs belonging to this account
      operationId: BudgetPrograms_list
      security:
      - OAuth2:
        - budgets.readonly
        - budgets
      summary: |2

        List Budget Programs
      tags:
      - Budget Programs
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-budget_programs
      x-accepts: application/json
    post:
      description: |2

        Creates a Budget Program.
        If your account does not have access to budget program features, a 403 response status will be returned.
        If this is the case and you want to gain access to this endpoint, please contact Brex support.
      operationId: BudgetPrograms_create
      security:
      - OAuth2:
        - budgets
      summary: |2

        Create Budget Program
      tags:
      - Budget Programs
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v1-budget_programs
      x-content-type: application/json
      x-accepts: application/json
  /v1/budget_programs/{id}:
    delete:
      description: "\nDelete a Budget Program by ID.\nThis endpoint requires budget\
        \ management. If your account does not have access to budget management features,\
        \ a 403 response status will be returned. \nIf this is the case and you want\
        \ to gain access to this endpoint, please contact Brex support.\n"
      operationId: BudgetPrograms_removeProgramById
      security:
      - OAuth2:
        - budgets
      summary: |2

        Delete Budget Program
      tags:
      - Budget Programs
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--v1-budget_programs-id
      x-accepts: application/json
    get:
      description: |2

        Retrieves a Budget Program by ID
      operationId: BudgetPrograms_getById
      security:
      - OAuth2:
        - budgets.readonly
        - budgets
      summary: |2

        Get Budget Program
      tags:
      - Budget Programs
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-budget_programs-id
      x-accepts: application/json
    put:
      description: "\nUpdates a Budget Program.\nThis endpoint requires budget management.\
        \ If your account does not have access to budget management features, a 403\
        \ response status will be returned. \nIf this is the case and you want to\
        \ gain access to this endpoint, please contact Brex support.\n"
      operationId: BudgetPrograms_updateProgramById
      security:
      - OAuth2:
        - budgets
      summary: |2

        Update Budget Program
      tags:
      - Budget Programs
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--v1-budget_programs-id
      x-content-type: application/json
      x-accepts: application/json
  /v1/budgets:
    get:
      description: |2

        Lists Budgets belonging to this account
      operationId: Budgets_list
      security:
      - OAuth2:
        - budgets.readonly
        - budgets
      summary: |2

        List Budgets
      tags:
      - Budgets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-budgets
      x-accepts: application/json
    post:
      description: "\nCreates a Budget.\nThis endpoint requires budget management.\
        \ If your account does not have access to budget management features, a 403\
        \ response status will be returned. \nIf this is the case and you want to\
        \ gain access to this endpoint, please contact Brex support.\n"
      operationId: Budgets_create
      security:
      - OAuth2:
        - budgets
      summary: |2

        Create Budget
      tags:
      - Budgets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v1-budgets
      x-content-type: application/json
      x-accepts: application/json
  /v1/budgets/{id}:
    get:
      description: |2

        Retrieves a Budget by ID
      operationId: Budgets_getById
      security:
      - OAuth2:
        - budgets.readonly
        - budgets
      summary: |2

        Get Budget
      tags:
      - Budgets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--v1-budgets-id
      x-accepts: application/json
    put:
      description: "\nUpdates a Budget.\nThis endpoint requires budget management.\
        \ If your account does not have access to budget management features, a 403\
        \ response status will be returned. \nIf this is the case and you want to\
        \ gain access to this endpoint, please contact Brex support.\n"
      operationId: Budgets_updateBudget
      security:
      - OAuth2:
        - budgets
      summary: |2

        Update Budget
      tags:
      - Budgets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--v1-budgets-id
      x-content-type: application/json
      x-accepts: application/json
  /v1/budgets/{id}/archive:
    post:
      description: |2

        Archives a budget, making it unusable for future expenses and removing it from the UI
      operationId: Budgets_archiveBudgetById
      security:
      - OAuth2:
        - budgets
      summary: |2

        Archive a budget
      tags:
      - Budgets
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--v1-budgets-id-archive
      x-accepts: application/json
components:
  securitySchemes:
    OAuth2:
      description: OAuth2 security scheme
      flows:
        authorizationCode:
          authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
          scopes:
            openid: openid
            offline_access: offline access
            budgets: View and manage budgets data
            budgets.readonly: View budgets data
          tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
      type: oauth2
      x-konfig-globally-required-security: true
x-explorer-enabled: false

